export default {
  metroLogo: require('../assets/images/metroLogo.png'),
  dropDown: require('../assets/images/dropDown.png'),
  menu: require('../assets/images/menu.png'),
  close: require('../assets/images/close.png'),
  telephone: require('../assets/images/telephone.png'),
  closeCircle: require('../assets/images/closeCircle.png'),
  openCircle: require('../assets/images/openCircle.png'),
  backBtn: require('../assets/images/backBtn.png'),
  exchange: require('../assets/images/exchange.png'),
  date: require('../assets/images/date.png'),
  time: require('../assets/images/time.png'),
  streetView: require('../assets/images/map_view.webp'),
  plus: require('../assets/images/plus.png'),
  minus: require('../assets/images/minus.png'),
  spashBGImg: require('../assets/images/SpashScreen.jpeg'),
  dirImg: require('../assets/images/direction.png'),
  supportImg: require('../assets/images/support.png'),
  mapSearchImg: require('../assets/images/mapSearch.png'),
  metroImg: require('../assets/images/metro.png'),
  rechargeImg: require('../assets/images/recharge.png'),
  clockImg: require('../assets/images/clock.png'),
  warningImg: require('../assets/images/warning.png'),
};
